//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_rondanet.wsRondanet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.rondanet.gs1uy.org/", ConfigurationName="wsRondanet.Rondanet")]
    public interface Rondanet {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ws_rondanet.wsRondanet.obtenerMensajesResponse obtenerMensajes(ws_rondanet.wsRondanet.obtenerMensajes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.obtenerMensajesResponse> obtenerMensajesAsync(ws_rondanet.wsRondanet.obtenerMensajes request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse enviarAcuseReciboMensajes(ws_rondanet.wsRondanet.enviarAcuseReciboMensajes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse> enviarAcuseReciboMensajesAsync(ws_rondanet.wsRondanet.enviarAcuseReciboMensajes request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ws_rondanet.wsRondanet.enviarMensajesResponse enviarMensajes(ws_rondanet.wsRondanet.enviarMensajes request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarMensajesResponse> enviarMensajesAsync(ws_rondanet.wsRondanet.enviarMensajes request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMensajes", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class obtenerMensajes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string formato;
        
        public obtenerMensajes() {
        }
        
        public obtenerMensajes(string usuario, string clave, string formato) {
            this.usuario = usuario;
            this.clave = clave;
            this.formato = formato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerMensajesResponse", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class obtenerMensajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public obtenerMensajesResponse() {
        }
        
        public obtenerMensajesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarAcuseReciboMensajes", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class enviarAcuseReciboMensajes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acuse;
        
        public enviarAcuseReciboMensajes() {
        }
        
        public enviarAcuseReciboMensajes(string usuario, string clave, string acuse) {
            this.usuario = usuario;
            this.clave = clave;
            this.acuse = acuse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarAcuseReciboMensajesResponse", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class enviarAcuseReciboMensajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public enviarAcuseReciboMensajesResponse() {
        }
        
        public enviarAcuseReciboMensajesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMensajes", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class enviarMensajes {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensajes;
        
        public enviarMensajes() {
        }
        
        public enviarMensajes(string usuario, string clave, string mensajes) {
            this.usuario = usuario;
            this.clave = clave;
            this.mensajes = mensajes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarMensajesResponse", WrapperNamespace="http://ws.rondanet.gs1uy.org/", IsWrapped=true)]
    public partial class enviarMensajesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rondanet.gs1uy.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public enviarMensajesResponse() {
        }
        
        public enviarMensajesResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RondanetChannel : ws_rondanet.wsRondanet.Rondanet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RondanetClient : System.ServiceModel.ClientBase<ws_rondanet.wsRondanet.Rondanet>, ws_rondanet.wsRondanet.Rondanet {
        
        public RondanetClient() {
        }
        
        public RondanetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RondanetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RondanetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RondanetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws_rondanet.wsRondanet.obtenerMensajesResponse ws_rondanet.wsRondanet.Rondanet.obtenerMensajes(ws_rondanet.wsRondanet.obtenerMensajes request) {
            return base.Channel.obtenerMensajes(request);
        }
        
        public string[] obtenerMensajes(string usuario, string clave, string formato) {
            ws_rondanet.wsRondanet.obtenerMensajes inValue = new ws_rondanet.wsRondanet.obtenerMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.formato = formato;
            ws_rondanet.wsRondanet.obtenerMensajesResponse retVal = ((ws_rondanet.wsRondanet.Rondanet)(this)).obtenerMensajes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.obtenerMensajesResponse> ws_rondanet.wsRondanet.Rondanet.obtenerMensajesAsync(ws_rondanet.wsRondanet.obtenerMensajes request) {
            return base.Channel.obtenerMensajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_rondanet.wsRondanet.obtenerMensajesResponse> obtenerMensajesAsync(string usuario, string clave, string formato) {
            ws_rondanet.wsRondanet.obtenerMensajes inValue = new ws_rondanet.wsRondanet.obtenerMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.formato = formato;
            return ((ws_rondanet.wsRondanet.Rondanet)(this)).obtenerMensajesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse ws_rondanet.wsRondanet.Rondanet.enviarAcuseReciboMensajes(ws_rondanet.wsRondanet.enviarAcuseReciboMensajes request) {
            return base.Channel.enviarAcuseReciboMensajes(request);
        }
        
        public string enviarAcuseReciboMensajes(string usuario, string clave, string acuse) {
            ws_rondanet.wsRondanet.enviarAcuseReciboMensajes inValue = new ws_rondanet.wsRondanet.enviarAcuseReciboMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.acuse = acuse;
            ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse retVal = ((ws_rondanet.wsRondanet.Rondanet)(this)).enviarAcuseReciboMensajes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse> ws_rondanet.wsRondanet.Rondanet.enviarAcuseReciboMensajesAsync(ws_rondanet.wsRondanet.enviarAcuseReciboMensajes request) {
            return base.Channel.enviarAcuseReciboMensajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarAcuseReciboMensajesResponse> enviarAcuseReciboMensajesAsync(string usuario, string clave, string acuse) {
            ws_rondanet.wsRondanet.enviarAcuseReciboMensajes inValue = new ws_rondanet.wsRondanet.enviarAcuseReciboMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.acuse = acuse;
            return ((ws_rondanet.wsRondanet.Rondanet)(this)).enviarAcuseReciboMensajesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ws_rondanet.wsRondanet.enviarMensajesResponse ws_rondanet.wsRondanet.Rondanet.enviarMensajes(ws_rondanet.wsRondanet.enviarMensajes request) {
            return base.Channel.enviarMensajes(request);
        }
        
        public string enviarMensajes(string usuario, string clave, string mensajes) {
            ws_rondanet.wsRondanet.enviarMensajes inValue = new ws_rondanet.wsRondanet.enviarMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.mensajes = mensajes;
            ws_rondanet.wsRondanet.enviarMensajesResponse retVal = ((ws_rondanet.wsRondanet.Rondanet)(this)).enviarMensajes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarMensajesResponse> ws_rondanet.wsRondanet.Rondanet.enviarMensajesAsync(ws_rondanet.wsRondanet.enviarMensajes request) {
            return base.Channel.enviarMensajesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ws_rondanet.wsRondanet.enviarMensajesResponse> enviarMensajesAsync(string usuario, string clave, string mensajes) {
            ws_rondanet.wsRondanet.enviarMensajes inValue = new ws_rondanet.wsRondanet.enviarMensajes();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.mensajes = mensajes;
            return ((ws_rondanet.wsRondanet.Rondanet)(this)).enviarMensajesAsync(inValue);
        }
    }
}
